### ISSUE TITLE
Could you add spacing after the jmol script

### ISSUE THREAD

**Issue by drjosephbaxter** [geoffrowland/moodle-filter_jmol#10]
Hi,

Our testers have raised an issue that anything after a jmol image has alignment issues.

They can of course fix this by adding line breaks them selves in the html editor. I was just wondering if you planned on adding spacing yourself so this is automatically done and so a non html savvy person does not have to deal with it.

Example: I added the word meh after the water jmol. As you can see if displays on the same line unless you edit the label in them mode and add line breaks.

![jmol](https://cloud.githubusercontent.com/assets/7721889/3732831/559ea81a-1701-11e4-8d48-c6cf24c8ad3b.png)

Cheers

Joe

**Comment by geoffrowland** [comment]
Try the latest master branch which has a significant upgrade of the Jmol/JSmol filter.
