### ISSUE TITLE
Broken Javascript inIE9

### ISSUE THREAD

**Issue by drjosephbaxter** [geoffrowland/moodle-filter_jmol#14]
Hi our testers have reported the following issue when using the JMOL plugin in IE9.

When opening a resource we are met with the following error from the jmol plugin:

![image](https://cloud.githubusercontent.com/assets/7721889/8875795/76273c2c-3213-11e5-94b3-a3a15aeeca13.png)

Moodle: 2.7.9
JMOL: 2015010201

**Comment by geoffrowland** [comment]
I'm not seeing this with IE10 in IE9 compatibility mode, though JSmol performance in IE9 is more sluggish than more up to date browsers. Do things work for you with IE10, Chrome, Firefox etc?
You could also try replacing the JSmol folder in the plugin with the latest stable version (14.2.15) from http://sourceforge.net/projects/jmol/files/Jmol/

I also hope to release a new version of the plugin, which adds features and addresses some other issues in the next few weeks

**Comment by drjosephbaxter** [comment]
Hi,

We have no problem with IE11, FF and Chrome.

It is not a major issue for us as the university will be upgrading all its IE9 machines to IE11 over the next couple of weeks :)

We look forwards to the next release.
