### ISSUE TITLE
Jmol filter conflicting with Glossaries

### ISSUE THREAD

**Issue by jkwchui** [geoffrowland/moodle-filter_jmol#9]
On a page with a Jmol-rendered molecule, auto-linked glossary entries are messed up.  Specifically, when a glossary entry was clicked on, some 8-10 popups appear in addition to the expected glossary popup; all these boxes have "alert" as the title, and the sole text is "confirm".
The anomalous behaviour disappears when the Jmol-rendered molecule is removed from the page.
Tested with Moodle 2.6, Jmol-filter master as of 8-Feb-2014.  The effect in question can be seen on the following page (accessible as Guest): http://chem.jon.hk/course/view.php?id=2&section=15

![screen shot 2014-02-11 at 9 58 05 am](https://f.cloud.github.com/assets/775675/2133243/02ee8736-92c0-11e3-9e5f-633fb58d112a.png)

**Comment by geoffrowland** [comment]
The latest master branch should fix this issue. Each Jmol/JSmol instance is now contained in its own iframe. This avoids conflicts with Glossary JavaScript. Jmol/JSmol instances can even be added to Glossary entries.
